### ISSUE TITLE
Transactional mail without From does not send

### ISSUE THREAD

**Issue by wongak** [mailjet/mailjet-apiv3-go#45]
Scenario:

- Sending a transactional mail
- using API v3.1 
- using a template
- sending without `From`

The request is accepted, but no mail is sent without errors.

**Comment by kmanchikov** [comment]
Hi there, 

I apologize for the belated answer. We are currently having an know issue over at our end, when it comes to using a Template without declaring additionally the "From" email address as a property in the Send API Call. 

So, with the above in mind and taking in consideration this issue, you should always use a "From" email address even though that is already declared during the creation of the Template. That could be used as a workaround until the issue is resolved from our end. 

Best, 
Krassimir

**Comment by tsidei** [comment]
Fixed in the API
